const ReviewActionTypes = {
    CREATE_REVIEW_START: 'CREATE_REVIEW_START',
    CREATE_REVIEW_SUCCESS: 'CREATE_REVIEW_SUCCESS',
    CREATE_REVIEW_FAILURE: 'CREATE_REVIEW_FAILURE',
    UPDATE_REVIEW_START: 'UPDATE_REVIEW_START',
    UPDATE_REVIEW_SUCCESS: 'UPDATE_REVIEW_SUCCESS',
    UPDATE_REVIEW_FAILURE: 'UPDATE_REVIEW_FAILURE',
    RESET_REVIEW_STATUS: 'RESET_REVIEW_STATUS',
};

export default ReviewActionTypes;