const RestaurantActionTypes = {
    CREATE_RESTAURANT_START: 'CREATE_RESTAURANT_START',
    CREATE_RESTAURANT_SUCCESS: 'CREATE_RESTAURANT_SUCCESS',
    CREATE_RESTAURANT_FAILURE: 'CREATE_RESTAURANT_FAILURE',
    UPDATE_RESTAURANT_START: 'UPDATE_RESTAURANT_START',
    UPDATE_RESTAURANT_SUCCESS: 'UPDATE_RESTAURANT_SUCCESS',
    UPDATE_RESTAURANT_FAILURE: 'UPDATE_RESTAURANT_FAILURE',
    RESET_RESTAURANT_STATUS: 'RESET_RESTAURANT_STATUS',
};

export default RestaurantActionTypes;