const RestaurantActionTypes = {
    CREATE_RESTAURANT_START: 'CREATE_RESTAURANT_START',
    CREATE_RESTAURANT_SUCCESS: 'CREATE_RESTAURANT_SUCCESS',
    CREATE_RESTAURANT_FAILURE: 'CREATE_RESTAURANT_FAILURE',
    RESET_CREATE_RESTAURANT_STATUS: 'RESET_CREATE_RESTAURANT_STATUS',
    UPDATE_RESTAURANT_START: 'UPDATE_RESTAURANT_START',
    UPDATE_RESTAURANT_SUCCESS: 'UPDATE_RESTAURANT_SUCCESS',
    UPDATE_RESTAURANT_FAILURE: 'UPDATE_RESTAURANT_FAILURE',
    RESET_UPDATE_RESTAURANT_STATUS: 'RESET_UPDATE_RESTAURANT_STATUS',
    REQUEST_ALL_RESTAURANTS_START: 'REQUEST_ALL_RESTAURANTS_START',
    REQUEST_ALL_RESTAURANTS_SUCCESS: 'REQUEST_ALL_RESTAURANTS_SUCCESS',
    REQUEST_ALL_RESTAURANTS_FAILURE: 'REQUEST_ALL_RESTAURANTS_FAILURE',
    REQUEST_FILTERED_RESTAURANTS: 'REQUEST_FILTERED_RESTAURANTS',
    RESET_FILTERED_RESTAURANTS: 'RESET_FILTERED_RESTAURANTS',
    RESET_KEYWORD: 'RESET_KEYWORD',
    SET_SORTBY_FILTER: 'SET_SORTBY_FILTER',
    RESET_SORTBY_FILTER: 'RESET_SORTBY_FILTER',
};

export default RestaurantActionTypes;